#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Amnesty.Resource", IsApplication=true)]

namespace Amnesty
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_gray = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo_transparent = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int splash = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splash2 = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001f
			public const int ButtonNext = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int ButtonPrev = 2131165214;
			
			// aapt resource value: 0x7f07003c
			public const int CheckBox1 = 2131165244;
			
			// aapt resource value: 0x7f070017
			public const int SumBic = 2131165207;
			
			// aapt resource value: 0x7f070011
			public const int SumChb1 = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int SumChb2 = 2131165203;
			
			// aapt resource value: 0x7f07001b
			public const int SumChb3 = 2131165211;
			
			// aapt resource value: 0x7f07000f
			public const int SumCity = 2131165199;
			
			// aapt resource value: 0x7f070008
			public const int SumEmail = 2131165192;
			
			// aapt resource value: 0x7f070019
			public const int SumEuro = 2131165209;
			
			// aapt resource value: 0x7f070015
			public const int SumIban = 2131165205;
			
			// aapt resource value: 0x7f070006
			public const int SumName = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int SumPostalcode = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int SumStreet1 = 2131165194;
			
			// aapt resource value: 0x7f070018
			public const int SummaryBic = 2131165208;
			
			// aapt resource value: 0x7f070012
			public const int SummaryChb1 = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int SummaryChb2 = 2131165204;
			
			// aapt resource value: 0x7f07001c
			public const int SummaryChb3 = 2131165212;
			
			// aapt resource value: 0x7f070010
			public const int SummaryCity = 2131165200;
			
			// aapt resource value: 0x7f070009
			public const int SummaryEmail = 2131165193;
			
			// aapt resource value: 0x7f07001a
			public const int SummaryEuro = 2131165210;
			
			// aapt resource value: 0x7f070016
			public const int SummaryIban = 2131165206;
			
			// aapt resource value: 0x7f070007
			public const int SummaryName = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int SummaryPostalcode = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int SummaryStreet1 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int SummaryStreet2 = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int app_title1 = 2131165188;
			
			// aapt resource value: 0x7f07002d
			public const int checkBox1 = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int checkBox2 = 2131165230;
			
			// aapt resource value: 0x7f070032
			public const int editTextBic = 2131165234;
			
			// aapt resource value: 0x7f07002a
			public const int editTextCity = 2131165226;
			
			// aapt resource value: 0x7f070023
			public const int editTextEmail = 2131165219;
			
			// aapt resource value: 0x7f070034
			public const int editTextEuro = 2131165236;
			
			// aapt resource value: 0x7f070030
			public const int editTextIban = 2131165232;
			
			// aapt resource value: 0x7f070021
			public const int editTextName = 2131165217;
			
			// aapt resource value: 0x7f070028
			public const int editTextPostalcode = 2131165224;
			
			// aapt resource value: 0x7f070025
			public const int editTextStreet1 = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int editTextStreet2 = 2131165222;
			
			// aapt resource value: 0x7f070003
			public const int imgAmnestyLogo = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int linearContainer = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int linearContainer2 = 2131165189;
			
			// aapt resource value: 0x7f07001d
			public const int linearContainer3 = 2131165213;
			
			// aapt resource value: 0x7f07002b
			public const int pageCount = 2131165227;
			
			// aapt resource value: 0x7f070001
			public const int relativeContainer = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int scrollContainer = 2131165184;
			
			// aapt resource value: 0x7f070035
			public const int textViewBedrag2 = 2131165237;
			
			// aapt resource value: 0x7f070031
			public const int textViewBic = 2131165233;
			
			// aapt resource value: 0x7f07002c
			public const int textViewChoices = 2131165228;
			
			// aapt resource value: 0x7f070029
			public const int textViewCity = 2131165225;
			
			// aapt resource value: 0x7f070022
			public const int textViewEmail = 2131165218;
			
			// aapt resource value: 0x7f070033
			public const int textViewEuro = 2131165235;
			
			// aapt resource value: 0x7f07002f
			public const int textViewIban = 2131165231;
			
			// aapt resource value: 0x7f070036
			public const int textViewLegal1 = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int textViewLegal2 = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int textViewLegal3 = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int textViewLegal4 = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int textViewLegal5 = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int textViewLegal6 = 2131165243;
			
			// aapt resource value: 0x7f070020
			public const int textViewName = 2131165216;
			
			// aapt resource value: 0x7f070027
			public const int textViewPostalcode = 2131165223;
			
			// aapt resource value: 0x7f070024
			public const int textViewStreet = 2131165220;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Fourth = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Second = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Third = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int app_title1 = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int btn_confirm = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int btn_control = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int btn_correct = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int btn_next = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int btn_prev = 2131034114;
			
			// aapt resource value: 0x7f050028
			public const int control_data = 2131034152;
			
			// aapt resource value: 0x7f050018
			public const int form_BIC = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int form_BIC_input = 2131034137;
			
			// aapt resource value: 0x7f050016
			public const int form_IBAN = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int form_IBAN_input = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int form_bedrag = 2131034138;
			
			// aapt resource value: 0x7f05001d
			public const int form_bedrag2 = 2131034141;
			
			// aapt resource value: 0x7f050013
			public const int form_choices = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int form_choices_input = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int form_choices_input2 = 2131034133;
			
			// aapt resource value: 0x7f050011
			public const int form_city = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int form_city_input = 2131034130;
			
			// aapt resource value: 0x7f050024
			public const int form_confirm = 2131034148;
			
			// aapt resource value: 0x7f05000a
			public const int form_email = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int form_email_input = 2131034123;
			
			// aapt resource value: 0x7f05001b
			public const int form_eurosign = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int form_eurosign_input = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int form_legal1 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int form_legal2 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int form_legal3 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int form_legal4 = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int form_legal5 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int form_legal6 = 2131034147;
			
			// aapt resource value: 0x7f050008
			public const int form_name = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int form_name_input = 2131034121;
			
			// aapt resource value: 0x7f05000f
			public const int form_postalcode = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int form_postalcode_input = 2131034128;
			
			// aapt resource value: 0x7f05000c
			public const int form_street = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int form_street_input1 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int form_street_input2 = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int form_title1 = 2131034119;
			
			// aapt resource value: 0x7f050025
			public const int pageOne = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int pageThree = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int pageTwo = 2131034150;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Amnesty_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
